export const APP_ROUTES = {
  login: "/login",
  home: "/",
  classrooms: "/classrooms",
  courses: "/courses",
  lecturers: "/lecturers",
  timetable: "/timetable",
  autoAssignment: "/auto-assignment",
  weeklySchedule: "/weekly-schedule",
  reports: "/reports",
  userManagement: "/user-management",
  settings: "/settings",
  staffDashboard: "/staff",
  staffSections: "/staff/sections",
  staffSchedule: "/staff/schedule",
  staffAllocation: "/staff/allocation",
  staffLookup: "/staff/lookup",
  staffBookings: "/staff/bookings",
  staffBookingList: "/staff/booking-list",
  lecturerDashboard: "/lecturer",
  lecturerRequests: "/lecturer/requests",
  employeeDashboard: "/employee",
  studentDashboard: "/student",
} as const;
